package com.ziguonnana.ziguserver.websocket.global.dto;

public enum CommandType {
    KEYWORD_TYPE, CHAT, BODYGAME_RESULT, BODYGAME_EXPLANIER, CHOICE, GAME_START, ART_START, ART_END, GAME_MODAL_START, AVATAR_CARD, POSE_TYPE
    ,IGUDONGSEONG_CYCLE, SHORTS_CHOICE, SHORTS_SPLITED, ART_RELAY
}
