package com.ziguonnana.ziguserver.websocket.global.dto;

public enum CommandType {
    KEYWORD_TYPE, CHAT, BODYGAME_RESULT, BODYGAME_EXPLANIER, CHOICE, GAME_START, ART_START, ART_END, GAME_MODAL_START, AVATAR_CARD, POSE_TYPE
    ,IGUDONGSEONG_CYCLE, SHORTS_CHOICE, SHORTS_SPLITED, ART_RELAY, SHORTS_MERGE, SHORTS_MERGE_COMPLETE, POSE_RESULT, POSE_END, SHORTS_RECORD_END
    ,DRAW_PREV
}
