package com.ziguonnana.ziguserver.websocket.answer.dto;

public enum SelfIntroductionQuestion {
    QUESTION1("큰 눈인가요, 작은 눈인가요?"),
    QUESTION2("쌍꺼풀이 있나요, 없나요?"),
    QUESTION3("높은 코인가요, 낮은 코인가요?"),
    QUESTION4("두꺼운 입술인가요, 얇은 입술인가요?"),
    QUESTION5("둥근 얼굴형인가요, 각진 얼굴형인가요?"),
    QUESTION6("밝은 피부톤인가요, 어두운 피부톤인가요?"),
    QUESTION7("진한 눈썹인가요, 연한 눈썹인가요?"),
    QUESTION8("긴 머리인가요, 짧은 머리인가요?"),
    QUESTION9("검은 머리인가요, 갈색 머리인가요?"),
    QUESTION10("직모인가요, 곱슬머리인가요?"),
    QUESTION11("큰 귀인가요, 작은 귀인가요?"),
    QUESTION12("고른 치아인가요, 불규칙한 치아인가요?"),
    QUESTION13("좁은 이마인가요, 넓은 이마인가요?"),
    QUESTION14("볼살이 있나요, 없나요?"),
    QUESTION15("날렵한 턱선인가요, 둥근 턱선인가요?"),
    QUESTION16("크고 둥근 눈인가요, 작고 날카로운 눈인가요?"),
    QUESTION17("검은 눈동자인가요, 갈색 눈동자인가요?"),
    QUESTION18("큰 입인가요, 작은 입인가요?"),
    QUESTION19("돌출된 광대뼈인가요, 평평한 광대뼈인가요?"),
    QUESTION20("매끈한 피부인가요, 울퉁불퉁한 피부인가요?"),
    QUESTION21("올라간 눈꼬리인가요, 내려간 눈꼬리인가요?"),
    QUESTION22("넓은 콧볼인가요, 좁은 콧볼인가요?"),
    QUESTION23("V라인 턱선인가요, 둥근 턱선인가요?"),
    QUESTION24("큰 손인가요, 작은 손인가요?"),
    QUESTION25("얇은 손가락인가요, 굵은 손가락인가요?"),
    QUESTION26("마른 체형인가요, 통통한 체형인가요?"),
    QUESTION27("넓은 어깨인가요, 좁은 어깨인가요?"),
    QUESTION28("긴 팔인가요, 짧은 팔인가요?"),
    QUESTION29("긴 다리인가요, 짧은 다리인가요?"),
    QUESTION30("큰 발인가요, 작은 발인가요?"),
    QUESTION31("진한 헤어라인인가요, 연한 헤어라인인가요?"),
    QUESTION32("탄력 있는 피부인가요, 처진 피부인가요?"),
    QUESTION33("주근깨가 있나요, 없나요?"),
    QUESTION34("가슴이 큰가요, 작은가요?"),
    QUESTION35("허벅지가 굵은가요, 얇은가요?"),
    QUESTION36("발목이 가는가요, 굵은가요?"),
    QUESTION37("허리가 가는가요, 두꺼운가요?"),
    QUESTION38("엉덩이가 큰가요, 작은가요?"),
    QUESTION39("목이 긴가요, 짧은가요?"),
    QUESTION40("눈이 날카로운가요, 부드러운가요?"),
    QUESTION41("턱에 보조개가 있나요, 없나요?"),
    QUESTION42("이목구비가 뚜렷한가요, 평범한가요?"),
    QUESTION43("머리숱이 많은가요, 적은가요?"),
    QUESTION44("곧은 다리인가요, 휜 다리인가요?"),
    QUESTION45("허벅지가 탄탄한가요, 부드러운가요?"),
    QUESTION46("피부가 건성인가요, 지성인가요?"),
    QUESTION47("머리가 곱슬인가요, 직모인가요?"),
    QUESTION48("코가 긴가요, 짧은가요?"),
    QUESTION49("턱이 뾰족한가요, 둥근가요?"),
    QUESTION50("웃을 때 보조개가 있나요, 없나요?"),
    QUESTION51("앞니가 고른가요, 비뚤어진가요?"),
    QUESTION52("피부가 하얀가요, 검은가요?"),
    QUESTION53("눈썹이 길고 풍성한가요, 짧고 얇은가요?"),
    QUESTION54("귀가 붙어있나요, 떨어져있나요?"),
    QUESTION55("팔이 굵은가요, 얇은가요?"),
    QUESTION56("다리가 곧은가요, 휜가요?"),
    QUESTION57("머리가 가는가요, 굵은가요?"),
    QUESTION58("손가락이 긴가요, 짧은가요?"),
    QUESTION59("발가락이 긴가요, 짧은가요?"),
    QUESTION60("머리카락이 부드러운가요, 거친가요?"),
    QUESTION61("피부에 점이 있나요, 없나요?"),
    QUESTION62("입꼬리가 올라갔나요, 내려갔나요?"),
    QUESTION63("얼굴에 홍조가 있나요, 없나요?"),
    QUESTION64("콧등이 높은가요, 낮은가요?"),
    QUESTION65("얼굴형이 계란형인가요, 사각형인가요?"),
    QUESTION66("광대뼈가 튀어나왔나요, 아닌가요?"),
    QUESTION67("눈동자가 밝은가요, 어두운가요?"),
    QUESTION68("웃을 때 눈가에 주름이 있나요, 없나요?"),
    QUESTION69("팔꿈치가 거친가요, 부드러운가요?"),
    QUESTION70("손톱이 길게 자라나요, 짧게 자라나요?"),
    QUESTION71("머리가 뻗친가요, 차분한가요?"),
    QUESTION72("앞머리가 있나요, 없나요?"),
    QUESTION73("눈꼬리가 올라갔나요, 내려갔나요?"),
    QUESTION74("이마에 주름이 있나요, 없나요?"),
    QUESTION75("입술에 점이 있나요, 없나요?"),
    QUESTION76("피부가 매끈한가요, 울퉁불퉁한가요?"),
    QUESTION77("목에 주름이 있나요, 없나요?"),
    QUESTION78("손목이 가늘어요, 굵어요?"),
    QUESTION79("머리숱이 풍성한가요, 적은가요?"),
    QUESTION80("눈동자가 둥근가요, 납작한가요?"),
    QUESTION81("팔뚝이 탄탄한가요, 부드러운가요?"),
    QUESTION82("어깨가 넓은가요, 좁은가요?"),
    QUESTION83("다리에 근육이 많은가요, 적은가요?"),
    QUESTION84("턱이 각졌나요, 둥근가요?"),
    QUESTION85("콧등이 뾰족한가요, 넓은가요?"),
    QUESTION86("입술이 촉촉한가요, 건조한가요?"),
    QUESTION87("이목구비가 뚜렷한가요, 평범한가요?"),
    QUESTION88("피부가 민감한가요, 건강한가요?"),
    QUESTION89("코끝이 뾰족한가요, 둥근가요?"),
    QUESTION90("눈동자가 큰가요, 작은가요?"),
    QUESTION91("광대뼈가 넓은가요, 좁은가요?"),
    QUESTION92("머리카락이 길어요, 짧아요?"),
    QUESTION93("손이 크나요, 작나요?"),
    QUESTION94("발이 크나요, 작나요?"),
    QUESTION95("머리 스타일이 파마인가요, 생머리인가요?"),
    QUESTION96("턱이 긴가요, 짧은가요?"),
    QUESTION97("콧구멍이 넓은가요, 좁은가요?"),
    QUESTION98("입이 넓은가요, 좁은가요?"),
    QUESTION99("턱선이 날카로운가요, 부드러운가요?"),
    QUESTION100("입술이 붉은가요, 옅은가요?"),
	QUESTION101("가장 좋아하는 취미는?"),
    QUESTION102("좋아하는 TV 시리즈는?"),
    QUESTION103("가장 좋아하는 계절은?"),
    QUESTION104("주로 듣는 음악 장르는?"),
    QUESTION105("가장 좋아하는 휴양지는?"),
    QUESTION106("좋아하는 자동차 브랜드는?"),
    QUESTION107("주로 사용하는 전자기기는?"),
    QUESTION108("가장 좋아하는 아이스크림 맛은?"),
    QUESTION109("좋아하는 커피 종류는?"),
    QUESTION110("좋아하는 스낵은?"),
    QUESTION111("좋아하는 꽃은?"),
    QUESTION112("가장 좋아하는 야식은?"),
    QUESTION113("자주 가는 여행지는?"),
    QUESTION114("좋아하는 패션 스타일은?"),
    QUESTION115("좋아하는 운동 시간대는?"),
    QUESTION116("좋아하는 조깅 장소는?"),
    QUESTION117("좋아하는 명절 음식은?"),
    QUESTION118("가장 좋아하는 애니메이션은?"),
    QUESTION119("가장 좋아하는 유튜버는?"),
    QUESTION120("좋아하는 음료수 브랜드는?"),
    QUESTION121("좋아하는 운동 기구는?"),
    QUESTION122("좋아하는 아침 식사는?"),
    QUESTION123("주로 쓰는 브라우저는?"),
    QUESTION124("좋아하는 디지털 기기는?"),
    QUESTION125("좋아하는 과일은?"),
    QUESTION126("가장 자주 가는 슈퍼마켓은?"),
    QUESTION127("가장 좋아하는 패스트푸드는?"),
    QUESTION128("좋아하는 음악 플레이어는?"),
    QUESTION129("좋아하는 서점은?"),
    QUESTION130("주로 사용하는 사진 앱은?"),
    QUESTION131("가장 좋아하는 채소는?"),
    QUESTION132("좋아하는 여행 스타일은?"),
    QUESTION133("좋아하는 스포츠 종목은?"),
    QUESTION134("가장 좋아하는 스포츠 경기장은?"),
    QUESTION135("가장 자주 사용하는 앱은?"),
    QUESTION136("좋아하는 스마트폰 브랜드는?"),
    QUESTION137("가장 좋아하는 명품 브랜드는?"),
    QUESTION138("좋아하는 게임 장르는?"),
    QUESTION139("주로 사용하는 화장품 브랜드는?"),
    QUESTION140("좋아하는 향기는?"),
    QUESTION141("가장 좋아하는 보드게임은?"),
    QUESTION142("좋아하는 야외 활동은?"),
    QUESTION143("주로 사용하는 택배사는?"),
    QUESTION144("가장 좋아하는 영화 배우는?"),
    QUESTION145("좋아하는 서점은?"),
    QUESTION146("좋아하는 뉴스 매체는?"),
    QUESTION147("좋아하는 웹툰은?"),
    QUESTION148("가장 좋아하는 전자기기는?"),
    QUESTION149("주로 사용하는 스트리밍 서비스는?"),
    QUESTION150("좋아하는 와인은?"),
    QUESTION151("좋아하는 맥주는?"),
    QUESTION152("가장 좋아하는 패션 아이템은?"),
    QUESTION153("좋아하는 롤모델은?"),
    QUESTION154("주로 사용하는 소셜 네트워크는?"),
    QUESTION155("좋아하는 건강식은?"),
    QUESTION156("좋아하는 간식은?"),
    QUESTION157("좋아하는 소셜 게임은?"),
    QUESTION158("가장 좋아하는 가구 브랜드는?"),
    QUESTION159("가장 자주 사용하는 모바일 앱은?"),
    QUESTION160("좋아하는 요일은?"),
    QUESTION161("좋아하는 시간대는?"),
    QUESTION162("가장 좋아하는 스포츠 팀은?"),
    QUESTION163("좋아하는 향수 브랜드는?"),
    QUESTION164("좋아하는 쇼핑몰은?"),
    QUESTION165("좋아하는 음반은?"),
    QUESTION166("좋아하는 디지털 카메라는?"),
    QUESTION167("좋아하는 조명 스타일은?"),
    QUESTION168("가장 좋아하는 날씨는?"),
    QUESTION169("좋아하는 영화 감독은?"),
    QUESTION170("가장 좋아하는 커피숍은?"),
    QUESTION171("좋아하는 와인 브랜드는?"),
    QUESTION172("좋아하는 텔레비전 쇼는?"),
    QUESTION173("좋아하는 만화는?"),
    QUESTION174("좋아하는 사진 촬영 스타일은?"),
    QUESTION175("가장 좋아하는 라디오 방송은?"),
    QUESTION176("좋아하는 디저트는?"),
    QUESTION177("좋아하는 드라마는?"),
    QUESTION178("좋아하는 그림 스타일은?"),
    QUESTION179("좋아하는 전시회는?"),
    QUESTION180("가장 좋아하는 휴일은?"),
    QUESTION181("좋아하는 스마트워치는?"),
    QUESTION182("가장 좋아하는 사진작가는?"),
    QUESTION183("좋아하는 해변은?"),
    QUESTION184("좋아하는 산책로는?"),
    QUESTION185("가장 좋아하는 운동 기구는?"),
    QUESTION186("좋아하는 간식 종류는?"),
    QUESTION187("가장 좋아하는 냉장고 브랜드는?"),
    QUESTION188("좋아하는 커피 원두는?"),
    QUESTION189("좋아하는 TV 뉴스는?"),
    QUESTION190("가장 좋아하는 휴가철은?"),
    QUESTION191("좋아하는 필름 카메라는?"),
    QUESTION192("좋아하는 빵 종류는?"),
    QUESTION193("좋아하는 수프는?"),
    QUESTION194("가장 좋아하는 패션 디자이너는?"),
    QUESTION195("좋아하는 선크림 브랜드는?"),
    QUESTION196("좋아하는 모바일 게임은?"),
    QUESTION197("가장 좋아하는 운동 선수는?"),
    QUESTION198("좋아하는 가방 브랜드는?"),
    QUESTION199("좋아하는 야구팀은?"),
    QUESTION200("좋아하는 농구팀은?");

    private final String question;

    SelfIntroductionQuestion(String question) {
        this.question = question;
    }

    public String getQuestion() {
        return question;
    }
}
