package com.ziguonnana.ziguserver.websocket.igudongseong.dto;

import java.util.Random;

public enum IgudongseongKeyword {
    HAPPY, SAD, ANGRY, EXCITED, TIRED, BORED, JOYFUL, ANXIOUS, CONFUSED, RELAXED,
    ENERGETIC, PEACEFUL, CURIOUS, NOSTALGIC, AMUSED, APATHETIC, AWKWARD, BRAVE, CALM, CHEERFUL,
    CLEVER, CONFIDENT, CONTENT, COURAGEOUS, DELIGHTED, EAGER, EMPATHETIC, FANTASTIC, FRIGHTENED,
    GLOOMY, GRATEFUL, GROUCHY, HOPEFUL, IMPATIENT, INSPIRED, JEALOUS, JOLLY, LAZY, LONELY,
    LOVED, LUCKY, MISERABLE, NERVOUS, OPTIMISTIC, OVERWHELMED, PATIENT, PROUD, QUIET,
    RELIEVED, RESTLESS, SATISFIED, SCARED, SERENE, SHOCKED, SILLY, SORROWFUL, STRESSED, SURPRISED,
    THANKFUL, THOUGHTFUL, TROUBLED, UNEASY, UPBEAT, UPSET, VIBRANT, WONDERFUL, WORRIED,
    YOUTHFUL, ZEALOUS, AMBITIOUS, ASHAMED, ASTONISHED, BLISSFUL, CAUTIOUS, COMFORTABLE,
    DISAPPOINTED, DISGUSTED, ELATED, EMBARRASSED, ENCHANTED, ENTHUSIASTIC, ENVIOUS,
    EXUBERANT, FASCINATED, FORLORN;

    private static final Random RANDOM = new Random();

    public static IgudongseongKeyword getRandomKeyword() {
        IgudongseongKeyword[] keywords = values();
        return keywords[RANDOM.nextInt(keywords.length)];
    }
}
